### ISSUE TITLE
sample run

### ISSUE THREAD

**Issue by csabiu** [damonge/CoLoRe#20]
I just compiled the code and now attempting to run the sample_run case. 
But I run into an issue......

[csabiu@polaris trunk]$ ./CoLoRe sample_run/param_colore.ini 
|-------------------------------------------------|
|                      CoLoRe                     |
|-------------------------------------------------|
CoLoRe: Couldn't open file sample_run/param_colore.ini

**Comment by vuitert** [comment]
Hi, I just installed CoLoRe and I am having the same problem...

**Comment by damonge** [comment]
Sorry, the test files in sample_run were very outdated. This is also the case for the README and a few other doc files, so let me know if you have any questions.

The latest commit should fix this specific issue. Just do ./CoLoRe sample_run/param.cfg

**Comment by csabiu** [comment]
working now. Thanks!
