### ISSUE TITLE
Add option to output line of sight skewers

### ISSUE THREAD

**Issue by andreufont** [damonge/CoLoRe#21]
With a fairly small amount of work, CoLoRe could become the best way to generate mocks for the study of the Lyman alpha forest in quasar surveys (like BOSS, eBOSS or DESI).

We would start by generating a light cone as usual, up to z = 4 or so, what means that the box will have a size of roughly 10 Gpc/h. At NERSC we were able to Gaussian fields with FFTW of size 7168^3, what gives a cell size of 1.4 Mpc/h. We could live with somewhat worse resolution if we wanted to add LPT, but for now we could move on with Gaussian fields.

We would then smooth the density field with a Gaussian somewhat larger than the cell size (say 2 or 3 Mpc/h), apply a lognormal transformation to the Gaussian field and populate the range 2 < z < 4 with quasars with a density of ~ 100 quasars per square degree. This means 4 million quasars distributed over the whole sphere. We would write their angular coordinates and redshift (including RSD) into a “catalog file”, potentially writing as well the corresponding HEALPix pixel (see below).

We would then convert the angular coordinates of each quasar into a high-resolution HEALPix map. The value of Nside would ideally be at least as large as 2^15 = 32768, corresponding to a pixel size of 0.1 arcminute, or transverse comoving separation of 120 kpc/h at z=2.5. The number of HEALPix pixels would be very large (> 1e10), but the majority of these would never be used.

Once we have identified the set of 4M pixels that correspond to quasar positions, we will compute the density and radial velocity skewers along these lines of sight. The spherical shells used to compute these lines of sight would be quite thin, ideally smaller than Delta r = 0.5 Mpc/h. This means that each skewer will have 10k pixels, containing two floats (density and velocity), for a total of 80 kb per quasar.

We will write these skewers into files, grouping them into a very coarse HEALPix binning of Nside=8 or so. Each group would have 5.2k quasars, resulting in files of size 400 Mb. Ideally the data format would be a FITS file with two tables: one containing densities as a function of line of sight pixel, and one containing velocities.

@slosar @dkirkby @fjaviersanchez

**Comment by damonge** [comment]
Check out the new "skewers" branch!

**Comment by andreufont** [comment]
A first version of this is already running, so we can close the issue and open new ones for specific changes when needed.

**Comment by andreufont** [comment]
Should we merge the skewers branch to master? Any reason to keep them separated?

(nothing urgent, but I don't want to forget this)
