### ISSUE TITLE
Make lighter skewer files by ignoring cells at z < z_skewer_cut 

### ISSUE THREAD

**Issue by andreufont** [damonge/CoLoRe#22]
Very often, when generating Lyman alpha mocks we don't need to store information below z=1.9 or so, but we are storing skewers with cells going all the way to z=0. It would be great to have an option (z_skewer_cut or similar), that could be set to the minimum redshift you'd like to store. 

Note that some times you might actually want to store all the information to z=0. For instance we might at some point be interested in cross-correlations of metals lines with low-z quasars, or things like that, but this would be an special case. I'd say that the default for z_skewer_cut should be set to 1.9.

**Comment by damonge** [comment]
@andreufont : sorry for my delay, been a bit offline for the last few weeks. I'll get on this and #21 ASAP.

**Comment by andreufont** [comment]
@damonge No worries at all, we are still testing code and playing around. This will only be critical once we start mass production of mocks.

**Comment by andreufont** [comment]
We already had multiple mass production runs and we never had a problem with disk space, so I'm closing this
