### ISSUE TITLE
Density correlation function of skewers have RSD

### ISSUE THREAD

**Issue by andreufont** [damonge/CoLoRe#33]
@jfarr03 ran a correlation function measurement on the density skewers (using the public code picca), and found that the correlation function measured was not isotropic. Instead, it showed the usual trend of linear redshift space distortions (RSD), with the line of sight correlation crossing zero on smaller scales, and the transverse being positive up to very large separations.

This is present in both the skewers branch and in the revamp/master branch, and I managed to reproduce the results on a different simulation.

It is possible that this is caused by some post-processing of the skewers, or a wrong usage of the code to measure the correlation function, but before digging too much into that we wanted to hear your opinion, @damonge, @fjaviersanchez. Is it possible that the skewers are using some sort of redshift space density???

**Comment by damonge** [comment]
That's strange. Could we see a plot of the result?

**Comment by andreufont** [comment]
First plot is from my run, using a very old simulation (from December, before the fix of mean delta).

[xi_wedges.pdf](https://github.com/damonge/CoLoRe/files/1646148/xi_wedges.pdf)

The second plot is from @jfarr03, using a very recent simulation after merging revamp into master:

[all_wedges_cf_exp_10_revamp_density_rmax160_n40_n40.pdf](https://github.com/damonge/CoLoRe/files/1646149/all_wedges_cf_exp_10_revamp_density_rmax160_n40_n40.pdf)

The wedges are slightly different, but you can see that both are anisotropic, and look like linear RSD.

**Comment by andreufont** [comment]
Actually, forget about it for now. There is clearly something off with these plots (they do not agree at all!), so we should spend some time figuring this out first.
We'll come back to you once we understand better the plots.

**Comment by andreufont** [comment]
Yes, I was also very surprised, since these measurements are directly on the skewer density (they didn't go through the DESI simulation code). I think we should test:
- run on Gaussian field, instead of lognormal, so that there is no redshift evolution (although I agree it shouldn't matter much).
- check cosmology assumed in picca, although I agree it shouldn't be THAT off (plus BAO peak looks in the right place). 

We'll come back to you!

**Comment by jfarr03** [comment]
@damonge @fjaviersanchez: fortunately this turned out to be an issue with the way with we were using picca, which was automatically projecting out long wavelength modes. Using a setting to prevent it from doing so solved the problem and the correlation functions now look much better!

**Comment by damonge** [comment]
Awesome, thanks for letting us know!
I'll close this, but feel free to reopen if things still look weird.
