### ISSUE TITLE
Issue in output_perpix when using a single MPI node

### ISSUE THREAD

**Issue by andreufont** [damonge/CoLoRe#35]
Hi @damonge - I wanted to try the new branch output_perpix (sorry I hadn't tried before, I actually forgot about it...). 

When I run it on my laptop, without MPI, it stops without any error message at the step where it re-distributes sources across nodes. In particular, this happens in function srcs_distribute_single, when it hits this line: 
    memcpy(&(par->cats_c[ipop]->ipix[i_sofar]),&(ipix_ordered[i0_in_nodes[node_to]]),

I'm trying to run it on Cori, where I could check if the code only crashes when using a single MPI task, but I need to reconfigure a couple of things so it might take a while...

**Comment by andreufont** [comment]
I've checked in Cori that the code runs fine when compiled with MPI flag, regardless of the number of MPI tasks used.

When compiled without the MPI flag in Cori, the error message is a Segmentation fault

**Comment by damonge** [comment]
Alright, I deleted this branch because it had departed too much from master and it would've been a nightmare to catch it up. If the per-pixel functionality is still desirable, I'm happy to try and reimplement it in the new code.
