### ISSUE TITLE
units of speed of light is strange

### ISSUE THREAD

**Issue by londumas** [damonge/CoLoRe#38]
Looking at the code, the units of speed of light are strange.
Is that true or simply a copy-past error?
https://github.com/damonge/CoLoRe/blob/43abfec9230bd6f37ec3498d499cc61195cb1e5d/src/cosmo_mad.h#L35

**Comment by damonge** [comment]
Ah, right. That should read c*H0^-1 in units of Mpc/h. I just fixed it (sorry for the delay)
