### ISSUE TITLE
Clean old test files

### ISSUE THREAD

**Issue by fjaviersanchez** [damonge/CoLoRe#40]
We have several copies of the same files to run the examples/test-suite of CoLoRe. We should eliminate these duplicates and streamline/document this.

**Comment by andreufont** [comment]
After we merge the branch from James, I could take a look at it and clean up the configuration files myself. I suspect we would want to have a couple of tests, a Lya-oriented and a LSST-oriented.

**Comment by damonge** [comment]
Doing some of this now in #44

**Comment by damonge** [comment]
Alright, everything is now self-contained and kind-of documented.
All the examples are found in the `examples` folder. It also contains a README file describing the different examples and scripts.
@andreufont : note that I've created a specific LSST example showing the kind of parameters/N(z)s/biases we'd like to generate simulations from.

**Comment by andreufont** [comment]
Great, I'll try running one of these!
