### ISSUE TITLE
FFTW_LIB and LIB_FFTW in Makefile

### ISSUE THREAD

**Issue by andreufont** [damonge/CoLoRe#48]
I noticed that in the Makefile you currently have 
FFTW_INC
FFTW_LIB
but also later on you define 
LIB_FFTW
Are they both necessary?

Also, I noticed that LIB_FFTW add twice the standard library:

endif #SINGLE_PRECISION
LIB_FFTW += -lfftw3

# for fftlog
LIB_FFTW += -lfftw3

It is a minor issue (the code compiles fine), but I thought we could use the current cleanup phase :-)

**Comment by damonge** [comment]
Yes, both are necessary. `FFTW_LIB` is basically the directory where the FFTW libraries are to be found (e.g. `/home/andreufont/software/lib/`, `LIB_FFTW` is a list containing all the FFTW libraries that are needed (e.g. `-lfftw3 -lfftw3_omp -lfftw3_mpi`).

Thanks for noticing the fftlog issue. I just fixed this in #50

**Comment by andreufont** [comment]
Great, I'll close the ticket then.
