### ISSUE TITLE
Number of populations

### ISSUE THREAD

**Issue by psilvaf** [damonge/CoLoRe#68]
I am running a loop to generate mocks. However, I keep getting the error:

`MPI task 14, Fatal: You're asking for too many populations 100! Enlarge NPOP_MAX`

Where can I write this specification 'NPOP_MAX'?I don't see anything about it in the doc.

**Comment by cramirezpe** [comment]
I successfully enlarged that value in the past modifying this line
https://github.com/damonge/CoLoRe/blob/d19ef73ef049d772918edb38c69ce632542cff6c/src/common.h#L133

and compiling again.

**Comment by psilvaf** [comment]
It worked!
Thanks! 🙂
